### ISSUE TITLE
Regraph success rate

### ISSUE THREAD

**Issue by hongfenglu** [AutodeskAILab/Fusion360GalleryDataset#69]
Hi, 

I tried to regraph the reconstruction dataset. Currently I ran through about 1384 json files. 687 of them are successfully regraphed, 446 of them raised some exceptions, and 242 of them are skipped. Are these numbers reasonable? Are a lot of AssertionErrors expected during regraph? Thanks in advance!

**Comment by karldd** [comment]
In short, yes this sounds right. Regraph extracts a face extrusion sequence from the data and that representation cannot exactly represent all shapes in the dataset. See also issue #67 and section 4.2 in the paper:

> Of the design sequences in the reconstruction dataset, 59.2% can be directly converted to a face extrusion sequence. We estimate that approximately 80% of designs in our dataset can be reconstructed by finding alternative construction sequences.

In order to avoid bad data we skip files and/or fail by test assertions when we check if we can reconstruct the geometry correctly.

For example consider these three possible sequences from the sketch on the left column:
![image](https://user-images.githubusercontent.com/619336/108386417-79bd2d80-71c1-11eb-9de9-b38d077a1c09.png)
A can be reconstructed because the faces we need for face extrusion exist in the final geometry (right). But B and C are not possible as the faces shown in red do not exist in the final geometry.

For the data used in the paper we manage to convert 5,108 of 8,625 designs successfully using Regraph. Here are the error stats from the conversion.

![image](https://user-images.githubusercontent.com/619336/108387079-1aabe880-71c2-11eb-86b7-998e91c6adb1.png)

If it is helpful we can provide this data.

**Comment by hongfenglu** [comment]
Thanks for the quick reply! Yes, it would be helpful if this data can be provided. 
As for the example, is it implying that Regraph can only return sequence of extrusions that use existing entire faces in the final geometry?

**Comment by karldd** [comment]
> Yes, it would be helpful if this data can be provided.

I'll work on preparing that data and post back.

> As for the example, is it implying that Regraph can only return sequence of extrusions that use existing entire faces in the final geometry?

The face extrusion action representation requires having a full face to extrude _from_  (blue face below) that exists in the final geometry. It also requires there to be another parallel face to extrude _to_ (yellow face below). 

![image](https://user-images.githubusercontent.com/619336/108803073-9ef9c500-754e-11eb-8551-7d76a3e145a8.png)


We estimate around 80% of the designs in the dataset can be represented this way. Although only 59.2% of designs can be directly converted using Regraph, we show in the paper we can reconstruct up to 67.5% of designs using neurally guided search to find alternate construction sequences. 

Finding alternate representations that can represent all shapes is an interesting area for future exploration.

**Comment by karldd** [comment]
I've updated the [Regraph readme](https://github.com/AutodeskAILab/Fusion360GalleryDataset/tree/master/tools/regraph#preprocessed-data) with a link to the pre-processed data we used in the paper. I'll go ahead and close this issue now, but feel free to reopen if you have further questions.
